channel_sources:
- freecad/label/dev,conda-forge,defaults
channel_targets:
- freecad dev
MACOSX_DEPLOYMENT_TARGET:  # [osx]
- '11.0'                   # [osx and arm64]
- '10.13'                  # [osx and x86_64]